### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(TestingUI_2Content)
add_subdirectory(TestingUI_2)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    TestingUI_2Contentplugin
    TestingUI_2plugin)